# Generated by Django 3.2 on 2023-04-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_at',
        ),
    ]
