# Generated by Django 3.2 on 2023-04-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='full_name',
        ),
    ]
